resource_group_name     = "Azure_Terraform_RG"
resource_group_location = "eastus"
app_service_plan_name   = "azureterraformappplan"
app_service_name        = "azureterraformsppservice"
sql_server_name         = "azureterraformsqlserver"
sql_database_name       = "azureterraformsqlDatabase"
sql_admin_login         = "sqladmin"
sql_admin_password      = "sql@password731"
storage_acc_name        = "azuretf0808241"

